// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type AppConfig struct {
	ID       int64
	DestPath string
}

type CollectPath struct {
	ID        int64
	Path      string
	ParentDir string
	CreatedAt string
}

type IgnorePattern struct {
	ID        int64
	Pattern   string
	CreatedAt string
}
