// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package database

import (
	"context"
)

const addCollectPath = `-- name: AddCollectPath :exec
INSERT INTO collect_paths (path, parent_dir) VALUES (?, ?)
`

type AddCollectPathParams struct {
	Path      string
	ParentDir string
}

func (q *Queries) AddCollectPath(ctx context.Context, arg AddCollectPathParams) error {
	_, err := q.db.ExecContext(ctx, addCollectPath, arg.Path, arg.ParentDir)
	return err
}

const addIgnorePath = `-- name: AddIgnorePath :exec
INSERT INTO ignore_regexps (regexp) VALUES (?)
`

func (q *Queries) AddIgnorePath(ctx context.Context, regexp string) error {
	_, err := q.db.ExecContext(ctx, addIgnorePath, regexp)
	return err
}

const getCollectPaths = `-- name: GetCollectPaths :many
SELECT id, path, parent_dir, created_at FROM collect_paths
`

func (q *Queries) GetCollectPaths(ctx context.Context) ([]CollectPath, error) {
	rows, err := q.db.QueryContext(ctx, getCollectPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectPath
	for rows.Next() {
		var i CollectPath
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.ParentDir,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIgnoreRegexps = `-- name: GetIgnoreRegexps :many
SELECT id, "regexp", created_at FROM ignore_regexps
`

func (q *Queries) GetIgnoreRegexps(ctx context.Context) ([]IgnoreRegexp, error) {
	rows, err := q.db.QueryContext(ctx, getIgnoreRegexps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IgnoreRegexp
	for rows.Next() {
		var i IgnoreRegexp
		if err := rows.Scan(&i.ID, &i.Regexp, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollectPath = `-- name: RemoveCollectPath :exec
DELETE FROM collect_paths WHERE id = ?
`

func (q *Queries) RemoveCollectPath(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeCollectPath, id)
	return err
}

const removeIgnoreRegexp = `-- name: RemoveIgnoreRegexp :exec
DELETE FROM ignore_regexps WHERE id = ?
`

func (q *Queries) RemoveIgnoreRegexp(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeIgnoreRegexp, id)
	return err
}
