// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package database

import (
	"context"
)

const addCollectPath = `-- name: AddCollectPath :exec
INSERT INTO collect_paths (path, parent_dir) VALUES (?, ?)
`

type AddCollectPathParams struct {
	Path      string
	ParentDir string
}

func (q *Queries) AddCollectPath(ctx context.Context, arg AddCollectPathParams) error {
	_, err := q.db.ExecContext(ctx, addCollectPath, arg.Path, arg.ParentDir)
	return err
}

const addIgnorePattern = `-- name: AddIgnorePattern :exec
INSERT INTO ignore_patterns (pattern) VALUES (?)
`

func (q *Queries) AddIgnorePattern(ctx context.Context, pattern string) error {
	_, err := q.db.ExecContext(ctx, addIgnorePattern, pattern)
	return err
}

const getAppConfig = `-- name: GetAppConfig :many
SELECT id, dest_path FROM app_config
`

func (q *Queries) GetAppConfig(ctx context.Context) ([]AppConfig, error) {
	rows, err := q.db.QueryContext(ctx, getAppConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppConfig
	for rows.Next() {
		var i AppConfig
		if err := rows.Scan(&i.ID, &i.DestPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectPaths = `-- name: GetCollectPaths :many
SELECT id, path, parent_dir, created_at FROM collect_paths
`

func (q *Queries) GetCollectPaths(ctx context.Context) ([]CollectPath, error) {
	rows, err := q.db.QueryContext(ctx, getCollectPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectPath
	for rows.Next() {
		var i CollectPath
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.ParentDir,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIgnorePatterns = `-- name: GetIgnorePatterns :many
SELECT id, pattern, created_at FROM ignore_patterns
`

func (q *Queries) GetIgnorePatterns(ctx context.Context) ([]IgnorePattern, error) {
	rows, err := q.db.QueryContext(ctx, getIgnorePatterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IgnorePattern
	for rows.Next() {
		var i IgnorePattern
		if err := rows.Scan(&i.ID, &i.Pattern, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollectPath = `-- name: RemoveCollectPath :exec
DELETE FROM collect_paths WHERE id = ?
`

func (q *Queries) RemoveCollectPath(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeCollectPath, id)
	return err
}

const removeIgnorePattern = `-- name: RemoveIgnorePattern :exec
DELETE FROM ignore_patterns WHERE id = ?
`

func (q *Queries) RemoveIgnorePattern(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeIgnorePattern, id)
	return err
}
